// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmx7HpSHwkuhWxYSoVnEMLc71dBDIgyEg',
    appId: '1:666856458652:web:92cdb47dc14d8aef832059',
    messagingSenderId: '666856458652',
    projectId: 'ems-app-a3d44',
    authDomain: 'ems-app-a3d44.firebaseapp.com',
    storageBucket: 'ems-app-a3d44.appspot.com',
    measurementId: 'G-NT0BRRZZDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-iXByx8ejQ9QmiiX9-xGX1dVIh_QmhRE',
    appId: '1:666856458652:android:d17874ff2c692d27832059',
    messagingSenderId: '666856458652',
    projectId: 'ems-app-a3d44',
    storageBucket: 'ems-app-a3d44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsWJiwGjav0hck_lmXCi5Ldj-79jmMGOM',
    appId: '1:666856458652:ios:f0eab0407fae3bf5832059',
    messagingSenderId: '666856458652',
    projectId: 'ems-app-a3d44',
    storageBucket: 'ems-app-a3d44.appspot.com',
    iosBundleId: 'com.example.centerSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsWJiwGjav0hck_lmXCi5Ldj-79jmMGOM',
    appId: '1:666856458652:ios:67e52d3df9f54b87832059',
    messagingSenderId: '666856458652',
    projectId: 'ems-app-a3d44',
    storageBucket: 'ems-app-a3d44.appspot.com',
    iosBundleId: 'com.example.centerSystem.RunnerTests',
  );
}
